config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
      resources :users
      resources :answers
      resources :questions
      resources :technologies
      resources :themes
      resources :user_answers
      resources :user_answer_histories
      resources :user_technologies
      resources :user_themes

      root to: "users#index"
    end
  resources :technologies do
    resources :themes
  end
  devise_for :users
  get 'static_pages/home'
  get 'static_pages/about'

  resources :user_technologies, only: [:index, :show, :update, :destroy] do
    resources :user_themes, only: [:show] do
      resources :user_answers, only: [:new, :create, :destroy, :index]
    end
  end

  root 'static_pages#home'
end

app/models/user_answer.rb
class UserAnswer < ApplicationRecord
  belongs_to :question
  belongs_to :answer
  belongs_to :user_theme
end

app/controllers/admin/user_answers_controller.rb
module Admin
  class UserAnswersController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = UserAnswer.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   UserAnswer.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/user_answers_controller.rb
class UserAnswersController < ApplicationController
  before_action :authenticate_user!
  def index
    @user_technology = UserTechnology.find(params[:user_technology_id])
    @user_theme = UserTheme.find(params[:user_theme_id])
    @questions = @user_theme.theme.questions
    @user_answers = UserAnswer.find_by(user_theme_id: @user_theme.id)
  end

  def new
    @user_technology = UserTechnology.find(params[:user_technology_id])
    @user_theme = UserTheme.find(params[:user_theme_id])
    @questions = @user_theme.theme.questions
    @user_answer = UserAnswer.new(user_theme_id: params[:user_theme_id])
  end

  def create
    @current_user = current_user
    @user_technology = UserTechnology.find(params[:user_technology_id])
    @user_theme = UserTheme.find(params[:user_theme_id])
    @questions = @user_theme.theme.questions

    params[:user_answer].each do |question_id, answer_ids|
      answers = answer_ids.reject { |e| e == "0" }
      user_answers = UserAnswer.where(user_theme_id: @user_theme.id, question_id: question_id, user_id: @current_user.id)

      UserAnswerHistory.where(user_theme_id: @user_theme.id, question_id: question_id, user_id: @current_user.id).in_batches do |user_answer_history_batch|
        user_answer_history_batch.delete_all
    end

      user_answers.each do |user_answer|
        UserAnswerHistory.create!(user_answer.attributes)
        user_answer.destroy
      end

      answers.each do |answer_id|
        @user_answer = UserAnswer.create!(user_theme_id: params[:user_theme_id], question_id: question_id, answer_id: answer_id, user_id: @current_user.id)
      end

    end
    render :index
  end
end

app/helpers/user_answers_helper.rb
module UserAnswersHelper
end

app/views/user_answers/index.html.slim
h2
  = "Your answers to the #{@user_technology.name} : #{@user_theme.name} theme:"
#result

= link_to "Retake test", new_user_technology_user_theme_user_answer_path(@user_technology, @user_theme)

table.table
  thead
    tr
      th
        | Question
      th
        | Your answer
      th
        | Correct answer
      th
        | Old data
  tbody
    - @questions.each do |question|
      tr.question_results
        td.question
          = question.question_text
        td.user_answer
          = question.user_answers(current_user)
        td.correct_answer
          = question.correct_answers
        td
          = question.user_answer_history(current_user)

app/views/user_answers/new.html.slim
= form_for([@user_technology, @user_theme, @user_answer]) do |form|
  - @questions.each do |question|
    = form.label :question, question.question_text
    br

    - question.answers.each do |answer|
      = answer.answer_text
      = form.check_box "#{question.id}", {checked: false, multiple: true}, answer.id
      br

  = form.submit