config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
      resources :users
      resources :answers
      resources :questions
      resources :technologies
      resources :themes
      resources :user_answers
      resources :user_answer_histories
      resources :user_technologies
      resources :user_themes

      root to: "users#index"
    end
  resources :technologies do
    resources :themes
  end
  devise_for :users
  get 'static_pages/home'
  get 'static_pages/about'

  resources :user_technologies, only: [:index, :show, :update, :destroy] do
    resources :user_themes, only: [:show] do
      resources :user_answers, only: [:new, :create, :destroy, :index]
    end
  end

  root 'static_pages#home'
end

app/models/technology.rb
class Technology < ApplicationRecord
  has_many :user_technologies
  has_many :users, through: :user_technologies

  has_many :themes
end

app/controllers/admin/technologies_controller.rb
module Admin
  class TechnologiesController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Technology.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Technology.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/technologies_controller.rb
class TechnologiesController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  def index
    @technologies = Technology.all
    authorize @technologies
  end

  def create
    @technology = Technology.new(technology_params)
    authorize @technology

    if @technology.save
      redirect_to action: :index, success: "Created successfully."
    else
      render action: :new
    end
  end

  def new
    @technology = Technology.new
    authorize @technology
  end

  def edit
    @technology = Technology.find(params[:id])
    authorize @technology
  end

  def show
    @technology = Technology.find(params[:id])
    authorize @technology
  end

  def update
    @technology = Technology.find(params[:id])
    authorize @technology

    if @technology.update_attributes(technology_params)
      redirect_to action: :show, id: @technology, success: "Updated successfully."
    else
      render action: :edit
    end
  end

  def destroy
    @technology = Technology.find(params[:id])
    authorize @technology
    UserTechnology.where(technology_id: params[:id]).destroy_all
    @technology.destroy
    redirect_to technologies_path, info: "Removed successfully."
  end

  private

  def technology_params
    params.require(:technology).permit(:name, :description)
  end
end

app/helpers/technologies_helper.rb
module TechnologiesHelper
end

app/views/technologies/_form.html.slim
= form_with(model: @technology, local: true) do |form|
  p
    = form.label :name
    = form.text_field :name
  p
    = form.label :description
    = form.text_area :description
  p
    = form.submit

app/views/technologies/edit.html.slim
h1
  | Technologies#edit
= render partial: "form"

app/views/technologies/index.html.slim
h1
  | Technologies
.btn
  = link_to "Create new", new_technology_path
table.table
  thead
    tr
      th
        | Name
      th[colspan="3"]
        | Actions
  tbody
    - @technologies.each do |technology|
      tr
        td
          = link_to technology.name, technology_path(technology)
        td
          = link_to "Apply", user_technology_path(technology), method: :put
          - if current_user&.admin?
            = link_to "Edit", edit_technology_path(technology)
            = link_to "Remove", technology_path(technology), method: :delete

app/views/technologies/new.html.slim
h1
  | Technologies#new
= render partial: "form"

app/views/technologies/show.html.slim
h2
  = "#{@technology.name} technology"
p
  = "Description: #{@technology.description}"
= link_to "New theme", new_technology_theme_path(@technology)
table.table
  thead
    tr
      th
        | Theme
      th
        | Progress
      th
        | Actions
  tbody
    - @technology.themes.each do |theme|
      tr
        td
          = link_to theme.name, technology_theme_path(id: theme.id, technology_id: @technology.id)
        td
          |  Progress_placeholder 
        td
          = link_to "Edit", edit_technology_theme_path(id: theme.id, technology_id: @technology.id)
          = link_to "Remove", technology_theme_path(id: theme.id, technology_id: @technology.id), method: :delete
= link_to "Edit", edit_technology_path
= link_to "Remove", technology_path(@technology), method: :delete, data: { confirm: "Are you sure?" }