config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
      resources :users
      resources :answers
      resources :questions
      resources :technologies
      resources :themes
      resources :user_answers
      resources :user_answer_histories
      resources :user_technologies
      resources :user_themes

      root to: "users#index"
    end
  resources :technologies do
    resources :themes
  end
  devise_for :users
  get 'static_pages/home'
  get 'static_pages/about'

  resources :user_technologies, only: [:index, :show, :update, :destroy] do
    resources :user_themes, only: [:show] do
      resources :user_answers, only: [:new, :create, :destroy, :index]
    end
  end

  root 'static_pages#home'
end

app/models/user_technology.rb
class UserTechnology < ApplicationRecord
  belongs_to :user
  belongs_to :technology
  has_many :user_themes, dependent: :destroy

  def name
    self.technology.name
  end
end

app/controllers/admin/user_technologies_controller.rb
module Admin
  class UserTechnologiesController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = UserTechnology.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   UserTechnology.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/user_technologies_controller.rb
class UserTechnologiesController < ApplicationController
  before_action :authenticate_user!
  def index
    @user = current_user
    @user_technologies = UserTechnology.where(user_id: @user.id)
  end

  def show
    @user = current_user
    @user_technology = UserTechnology.find_by(id: params[:id], user_id: @user.id)
  end

  def update
    # add handler for ":no_content"
    @user = current_user
    @technology = Technology.find(params[:id])
    @user_technology = UserTechnology.find_by(user_id: @user.id, technology_id: @technology.id)
    if @user_technology.nil?
      @user_technology = UserTechnology.create!(user_id: @user.id, technology_id: @technology.id)

      @technology.themes.each do |theme|
        UserTheme.create!(user_id: @user.id, theme_id: theme.id, user_technology_id: @user_technology.id)
      end
    end
  end

  def destroy
    @user = current_user
    @user_technology = UserTechnology.find_by(user_id: @user.id, id: params[:id])
    if @user_technology
      @user_technology.destroy
      redirect_to user_technologies_path, success: "Removed successfully."
    end
  end
end

app/helpers/user_technologies_helper.rb
module UserTechnologiesHelper
end

app/views/user_technologies/index.html.slim
h2
  | My technologies
table.table
  thead
    tr
      th
        | Name
      th
        | Action
  tbody
    - @user_technologies.each do |user_technology|
      tr
        td
          = link_to user_technology.name, user_technology_path(user_technology.id)
        td
          = link_to "Remove", user_technology_path(user_technology.id), method: :delete, data: { confirm: "Are yoyu sure?" }

app/views/user_technologies/show.html.slim
h2
  = "Technology: #{@user_technology.technology.name}"
table.table
  thead
    tr
      th
        | Name
      th
        | Action
  tbody
    - @user_technology.user_themes.each do |user_theme|
      tr
        td
          = link_to user_theme.theme.name, user_technology_user_theme_path(@user_technology, user_theme)